spring.application.name=Uber-BookingService

spring.datasource.url=jdbc:mysql://localhost:3306/uber_db_local 

spring.datasource.username=root
spring.datasource.password=arkaprava15
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
server.port=7475

eureka.client.service-url.defaultZone=http://localhost:8061/eureka
eureka.instance.prefer-ip-address=true